name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main # Adjust this to your default branch if it's not main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Ensure compatibility with your project

      - name: Install dependencies
        run: yarn install

      - name: Build site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
